package ANOP

def ACLE = getFieldByName("Add Client legal entities")
def CLE2 = getFieldByName("Client legal entity 2")
def CCN2 = getFieldByName("Client contact 2")
def CLE3 = getFieldByName("Client legal entity 3")
def CCN3 = getFieldByName("Client contact 3")
def CLE4 = getFieldByName("Client legal entity 4")
def CCN4 = getFieldByName("Client contact 4")
def CLE5 = getFieldByName("Client legal entity 5")
def CCN5 = getFieldByName("Client contact 5")
def CLE6 = getFieldByName("Client legal entity 6")
def CCN6 = getFieldByName("Client contact 6")

CLE2.setHidden(true)
CLE2.setRequired(false)
CCN2.setHidden(true)
CCN2.setRequired(false)
CLE3.setHidden(true)
CLE3.setRequired(false)
CCN3.setHidden(true)
CCN3.setRequired(false)
CLE4.setHidden(true)
CLE4.setRequired(false)
CCN4.setHidden(true)
CCN4.setRequired(false)
CLE5.setHidden(true)
CLE5.setRequired(false)
CCN5.setHidden(true)
CCN5.setRequired(false)
CLE6.setHidden(true)
CLE6.setRequired(false)
CCN6.setHidden(true)
CCN6.setRequired(false)

def ACLEOption = ACLE.getValue()

if (ACLEOption == "1"){
    CLE2.setRequired(true)
    CLE2.setHidden(false)
    CCN2.setHidden(false)
    CLE3.setFormValue("")
    CCN3.setFormValue("")
    CLE4.setFormValue("")
    CCN4.setFormValue("")
    CLE5.setFormValue("")
    CCN5.setFormValue("")
    CLE6.setFormValue("")
    CCN6.setFormValue("")
}
else if (ACLEOption == "2"){
    CLE2.setRequired(true)
    CLE2.setHidden(false)
    CCN2.setHidden(false)
	CLE3.setRequired(true)
    CLE3.setHidden(false)
    CCN3.setHidden(false)
    CLE4.setFormValue("")
    CCN4.setFormValue("")
    CLE5.setFormValue("")
    CCN5.setFormValue("")
    CLE6.setFormValue("")
    CCN6.setFormValue("")
}
else if (ACLEOption == "3"){
    CLE2.setRequired(true)
    CLE2.setHidden(false)
    CCN2.setHidden(false)
	CLE3.setRequired(true)
    CLE3.setHidden(false)
    CCN3.setHidden(false)
	CLE4.setRequired(true)
    CLE4.setHidden(false)
    CCN4.setHidden(false)
    CLE5.setFormValue("")
    CCN5.setFormValue("")
    CLE6.setFormValue("")
    CCN6.setFormValue("")
}
else if (ACLEOption == "4"){
    CLE2.setRequired(true)
    CLE2.setHidden(false)
    CCN2.setHidden(false)
	CLE3.setRequired(true)
    CLE3.setHidden(false)
    CCN3.setHidden(false)
	CLE4.setRequired(true)
    CLE4.setHidden(false)
    CCN4.setHidden(false)
	CLE5.setRequired(true)
    CLE5.setHidden(false)
    CCN5.setHidden(false)
    CLE6.setFormValue("")
    CCN6.setFormValue("")
}
else if (ACLEOption == "5"){
    CLE2.setRequired(true)
    CLE2.setHidden(false)
    CCN2.setHidden(false)
	CLE3.setRequired(true)
    CLE3.setHidden(false)
    CCN3.setHidden(false)
	CLE4.setRequired(true)
    CLE4.setHidden(false)
    CCN4.setHidden(false)
	CLE5.setRequired(true)
    CLE5.setHidden(false)
    CCN5.setHidden(false)
	CLE6.setRequired(true)
    CLE6.setHidden(false)
    CCN6.setHidden(false)
}
else{
    CLE2.setFormValue("")
    CCN2.setFormValue("")
    CLE3.setFormValue("")
    CCN3.setFormValue("")
    CLE4.setFormValue("")
    CCN4.setFormValue("")
    CLE5.setFormValue("")
    CCN5.setFormValue("")
    CLE6.setFormValue("")
    CCN6.setFormValue("")
    CLE2.setHidden(true)
	CCN2.setHidden(true)
    CLE3.setHidden(true)
	CCN3.setHidden(true)
    CLE4.setHidden(true)
	CCN4.setHidden(true)
    CLE5.setHidden(true)
	CCN5.setHidden(true)
    CLE6.setHidden(true)
	CCN6.setHidden(true)
}